version: "3.8" 
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    networks:
      - cms-proxy
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=http://localhost:3070
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3070:3070
    networks:
      - cms-proxy
      - cms-backnet
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://3080:3080
    command: /usr/app/node_modules/.bin/nodemon -L src/index.js
    restart: unless-stopped

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - cms-backnet
    volumes:
      - mongo-data:/data/db
    restart: always

networks:
  cms-proxy:
    driver: host
  cms-backnet:
    driver: host

volumes:
  mongo-data:
    driver: local
