version: "3.8" 
services:
  # REACT
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: npm start
    ports:
      - 3080:3080
    networks:
      - cms-proxy
    volumes:
      - /server/school/cms/frontend:/usr/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER=http://backend:3070
      - DEBUG=cms-frontend:*
      - PORT=3080
      
  # EXPRESS
  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
    command: npm run start:dev
    ports:
      - 3070:3070
    networks:
      - cms-proxy
      - cms-backnet
    volumes:
      - /server/school/cms/backend:/usr/app
    # depends_on:
    #   - db
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://frontend:3080
      - DEBUG=cms-backend:*
      - PORT=3070

  # MONGODB
  # db:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - cms-backnet
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: always

networks:
  cms-proxy:
    external: true
  cms-backnet:
    external: true

# volumes:
#   mongo-data:
#     external: true
