global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    network: cms-proxy

log:
  level: DEBUG
  format: common

accessLog:
  filePath: /etc/traefik/logs/access.log
  bufferingSize: 100
  format: json

entryPoints:
  web:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: "websecure"
#          scheme: "https"
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - 173.245.48.0/20
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
