@domain = http://localhost:5070
@id = 102073
@courseId = 1919

GET {{domain}}/api/user/{{id}}/profile

###


GET {{domain}}/api/user/{{id}}/enrollments


### 

GET {{domain}}/api/user/{{id}}/course/{{courseId}}/assignments


###

GET {{domain}}/api/user/{{id}}/course/{{courseId}}/announcements